# Generated by Django 3.2.18 on 2023-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20230427_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
