# Generated by Django 3.2.18 on 2023-04-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=1, upload_to='productos/'),
            preserve_default=False,
        ),
    ]
